# Generated by Django 4.0.2 on 2022-02-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('quiz_id', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('incorrect_answers', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=200)),
            ],
        ),
    ]
